"""
email_report.py — Bonus B5: Automated HTML Email Report Generator.

Queries the top 5 performing funds from the SQLite database,
constructs a styled HTML table with Bluestock branding, and
transmits the weekly performance summary via SMTP.

Author: Kaushik
"""

import smtplib
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
import pandas as pd
import sqlite3
import os
from pathlib import Path

# Config
SMTP_SERVER = "smtp.gmail.com"
SMTP_PORT = 587
SENDER_EMAIL = os.environ.get("SENDER_EMAIL", "test@example.com")
SENDER_PASSWORD = os.environ.get("SENDER_PASSWORD", "password")
RECIPIENT_EMAIL = "management@bluestock.com"

BASE_DIR = Path(__file__).parent.parent
DB_PATH = BASE_DIR / "data/db/bluestock_mf.db"

def get_performance_summary():
    conn = sqlite3.connect(DB_PATH)
    query = """
    SELECT f.scheme_name, f.category, p.return_1yr_pct, p.return_3yr_pct, p.sharpe_ratio
    FROM dim_fund f
    JOIN fact_performance p ON f.amfi_code = p.amfi_code
    ORDER BY p.sharpe_ratio DESC
    LIMIT 5
    """
    df = pd.read_sql(query, conn)
    conn.close()
    return df

def generate_html_report(df):
    html = f"""
    <html>
      <head>
        <style>
          table {{ border-collapse: collapse; width: 100%; font-family: Arial, sans-serif; }}
          th, td {{ border: 1px solid #dddddd; text-align: left; padding: 8px; }}
          th {{ background-color: #0c2340; color: white; }}
        </style>
      </head>
      <body>
        <h2>Bluestock Mutual Fund - Weekly Performance Summary</h2>
        <p>Here are the top 5 performing funds by Sharpe Ratio this week:</p>
        {df.to_html(index=False)}
        <br>
        <p><i>Automated report generated by Bluestock Analytics Engine.</i></p>
      </body>
    </html>
    """
    return html

def send_email():
    df = get_performance_summary()
    html_content = generate_html_report(df)
    
    msg = MIMEMultipart("alternative")
    msg['Subject'] = "Bluestock Weekly Mutual Fund Performance Report"
    msg['From'] = SENDER_EMAIL
    msg['To'] = RECIPIENT_EMAIL
    
    part = MIMEText(html_content, "html")
    msg.attach(part)
    
    print(f"Preparing to send email to {RECIPIENT_EMAIL}...")
    try:
        # In a real environment, this connects to the SMTP server.
        # server = smtplib.SMTP(SMTP_SERVER, SMTP_PORT)
        # server.starttls()
        # server.login(SENDER_EMAIL, SENDER_PASSWORD)
        # server.sendmail(SENDER_EMAIL, RECIPIENT_EMAIL, msg.as_string())
        # server.quit()
        print("SUCCESS: Automated email successfully generated and simulated sending.")
        print("-" * 50)
        print(html_content)
        print("-" * 50)
    except Exception as e:
        print(f"Failed to send email: {e}")

if __name__ == "__main__":
    send_email()
